name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Publish Feed API Service to Registry
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ichdamola/udagram-api-feed
        tags: v1, adedamola-udagram-api-feed
        registry: hub.docker.com/repository/docker
        dockerfile: ./udagram-api-feed/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     
        
   
