name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: building feed api
      run: docker build -t udagram-api-feed ./udagram-api-feed
      
    - name: tagging feed api
      run: docker tag udagram-api-feed ichdamola/udagram-api-feed:adedamola-udagram-api-feed-v1.0
      
    - name: Logging in
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        
    - name: Pushing to Docker Hub
      run: docker push udagram-api-feed ichdamola/udagram-api-feed:adedamola-udagram-api-feed-v1.0
      
   
