name: ci

on:
  push:
    branches:
      - 'main'

# Building Services Images
- docker build -t udagram-api-feed ./udagram-api-feed
- docker build -t udagram-api-user ./udagram-api-user
- docker build -t udagram-frontend ./udagram-frontend
- docker build -t udagram-reverseproxy ./udagram-reverseproxy

# Tagging Services Containers
- docker tag udagram-api-feed ichdamola/udagram-api-feed:adedamola-udagram-api-feed-v1.0
- docker tag udagram-api-user ichdamola/udagram-api-user:adedamola-udagram-api-user-v1.0
- docker tag udagram-frontend ichdamola/udagram-frontend:adedamola-udagram-frontend-v1.0
- docker tag udagram-reverseproxy ichdamola/reverseproxy:adedamola-udagram-reverseproxy-v1.0

# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

# Pushing Services Containers
- docker push udagram-api-feed ichdamola/udagram-api-feed:adedamola-udagram-api-feed-v1.0
- docker push udagram-api-user ichdamola/udagram-api-user:adedamola-udagram-api-feed-v1.0
- docker push udagram-frondend ichdamola/udagram-frontend:adedamola-udagram-frontend-v1.0
- docker push udagram-reverseproxy ichdamola/reverseproxy:adedamola-udagram-reverseproxy-v1.0
# Do similar for other three images
